[neo-space-city]
id = 900002100
alias = 42015635
name = "Neo Space City"
type = "spell field"
effect = """\
(This card's name is always treated as "Neo Space".)
When this card is activated: \
    You can add from your Deck to you hand, \
    1 "Neo-Spacian" monster or 1 Spell/Trap that lists it, \
    except "{CARD_NAME}". \
If a Fusion Monster(s) you control that lists "Elemental HERO Neos" as material \
    is destroyed by battle, or leaves the field because of a card effect: \
    You can Special Summon 1 "Elemental HERO Neos" from your hand, Deck, Extra Deck, or GY, \
    ignoring its Summoning conditions and treated as Special Summoned properly. \
You can only use each above effects of "{CARD_NAME}" once per turn. \
Fusion Monsters that lists "Elemental HERO Neos" as material do not have to activate their effects during the End Phase \
    that shuffle them into the Extra Deck. \
This card and face-up Continuous Spell/Trap Card(s) in your Spell & Trap Zone \
    are unaffected by other "Neos" cards' effects. \
    This effect cannot be negated. \
"""
strings = [
    "Add 1 \"Neo-Spacian\" monster or Spell/Trap that lists it to your hand?",
    "Special Summon \"Elemental HERO Neos\"",
]

[elemental-hero-astrum-neos]
id = 900002101
alias = 89943723
name = "Elemental HERO Astrum Neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2500
def = 2000
effect = """\
(This card's name is always treated as "Elemental HERO Neos".)
1 "HERO" monster + 1 Level 5 or lower monster
Must first be either Fusion Summoned, or Special Summoned by shuffling 1 Level 7 "Neos" monster you control into the Deck. \
If this card is Special Summoned from the Extra Deck: \
    You can Special Summon 1 "Neo-Spacian" monster from your hand, but it cannot attack this turn, \
    and if you do, this card gains ATK equal to that monster's ATK until the end of your opponent's turn, \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[elemental-hero-miracle-neos]
id = 900002102
rarity = "gold"
name = "Elemental HERO Miracle Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "divine"
race = "warrior"
level = 12
atk = 2500
def = 2500
effect = """\
1 Level 7 "Neos" Normal Monster + 4+ "Neo-Spacian" monsters with different Attributes
Must be Fusion Summoned with the above materials. \
This card's Fusion Summon cannot be negated. \
You can only control 1 "{CARD_NAME}". \
Your opponent cannot Tribute it, or use it as material for an Summon. \
Control of it cannot switch. \
Fusion Monsters that lists "Elemental HERO Neos" as material \
    do not have to activate their effects during the End Phase that shuffle them into the Extra Deck. \
The above effects cannot be negated or be copied. \
If this card is Fusion Summoned: \
    You can banish any number of "Neo-Spacian" monster or Level 7 "Neos" Fusion Monster \
    from your GY and/or Extra Deck, up to the number of material used for its Summon, \
    and if you do, this card gains monster's effect and 500 original ATK/DEF for each banished monster. \
    Your opponent cannot activate cards or effects in response to this effect's activation. \
If this card is Fusion Summoned using 6 or more "Neo-Spacian" monsters, \
    it is unaffected by other cards' effect. \
"""
strings = ["Fusion Summoned using 6+ \"Neo-Spacian\" monster"]

[elemental-hero-abyss-neos]
id = 900002103
name = "Elemental HERO Abyss Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Dark Panther" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    Banish all cards in your opponent's Spell/Trap Zone or Monster Zone \
    (whichever has more, your choice, if tied). \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    send all cards on the field to the GY. \
"""
strings = [
    "Banish all cards in your opponent's Spell/Trap Zone or Monster Zone",
    "Banish cards in Spell/Trap Zone",
    "Banish cards in Monster Zone",
]

[elemental-hero-steam-neos]
id = 900002104
name = "Elemental HERO Steam Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin" + "Neo-Spacian Flare Scarab"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn, when another card, or its effect, is activated (Quick Effect): \
    You can negate the activation, and if you do, destroy that card, \
    and if you do that, this card gain 400 ATK. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    neither player can declare an attack until the end of the next turn. \
"""
strings = [
    "Negate the activation and destroy & gain ATK",
    "Affected by effect \"{CARD_NAME}\": cannot declare an attack",
]

[elemental-hero-stratumine-neos]
id = 900002105
name = "Elemental HERO Stratumine Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "water"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin" + "Neo-Spacian Grand Mole"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
Once per turn: You can shuffle into the Deck, \
    1 other card from either player's hand, field, or GY. \
    (The card in your opponent's hand is chosen at random). \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    shuffle all banished cards into the Deck(s). \
"""
strings = [
    "Shuffle 1 card into the Deck",
    "Shuffle card on field, either GY, or your hand",
    "Shuffle random card in your opponent's hand",
]

[elemental-hero-hellfire-neos]
id = 900002106
name = "Elemental HERO Hellfire Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "fire"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Flare Scarab" + "Neo-Spacian Dark Panther"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    destroy another cards on the field up to the number of Spells/Traps on the field, \
    and if you do, this card gains 400 ATK for each destroyed card. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    negate the effects of all face-up monsters on the field. \
"""
strings = []

[elemental-hero-nimbus-neos]
id = 900002107
name = "Elemental HERO Nimbus Neos"
set = "elemental-hero neos"
type = "monster fusion effect"
attribute = "light"
race = "warrior"
level = 9
atk = 3000
def = 2500
effect = """\
"Elemental HERO Neos" + "Neo-Spacian Glow Moss" + "Neo-Spacian Air Hummingbird"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. \
    (You do not use "Polymerization".) \
If this card is Special Summoned from the Extra Deck: \
    You can banish 1 face-up monster on the field until the end of the next turn, \
    then gain LP equal to the original ATK of that monster. \
Once per turn, during the End Phase: \
    Shuffle this card into the Extra Deck, and if you do, \
    each player draws until they have 5 cards in their hand. \
"""
strings = []

[elemental-hero-neos-armiger]
id = 900002108
name = "Elemental HERO Neos Armiger"
set = "elemental-hero neos"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1900
def = 1300
effect = """\
While "Neo Space" is on the field, this card's name becomes "Elemental HERO Neos" while on the field or in the GY. \
    This effect cannot be negated. \
When this card is Normal or Special Summoned: \
    You can add 1 "Elemental HERO Neos" or 1 Spell/Trap that mentions it your Deck to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[elemental-hero-wingman]
id = 900002109
alias = 21844576
name = "Elemental HERO Wingman"
set = "elemental-hero wingman"
type = "monster effect"
attribute = "wind"
race = "warrior"
level = 3
atk = 1000
def = 1000
effect = """\
(This card's name is always treated as "Elemental HERO Avian".)
This card is treated as a Normal Monster while face-up on the field or in the hand or GY. \
If this card is in your hand or GY: You can discard 1 other "HERO" monster; \
    Special Summon this card, but banish it when it leaves the field. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● This card gains 400 ATK.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[elemental-hero-blazinatrix]
id = 900002110
alias = 58932615
name = "Elemental HERO Blazinatrix"
set = "elemental-hero"
type = "monster effect"
attribute = "fire"
race = "warrior"
level = 3
atk = 1200
def = 800
effect = """\
(This card's name is always treated as "Elemental HERO Burstinatrix".)
This card is treated as a Normal Monster while face-up on the field or in the hand, GY. \
You can return this card you control to your hand; \
    Special Summon 1 "HERO" monster from your hand, except "Elemental HERO Burstinatrix". \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● This card can attack all monsters your opponent controls, once each.
"""
strings = [
    "Summoned using \"{CARD_NAME}\"",
    "Return to hand & Special Summon 1 \"HERO\" monster from your hand",
]

[elemental-hero-boulderman]
id = 900002111
alias = 84327329
name = "Elemental HERO Boulderman"
set = "elemental-hero"
type = "monster effect"
attribute = "earth"
race = "warrior"
level = 4
atk = 800
def = 2000
effect = """\
(This card's name is always treated as "Elemental HERO Clayman".)
This card is treated as a Normal Monster while face-up on the field or in the hand, GY. \
(Quick Effect): You can discard this card; \
    until the end of this turn, "HERO" monsters you control cannot be destroyed by battle. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● Once per turn (Quick Effect): You can target 1 monster your opponent controls; it loses 800 ATK and DEF.
"""
strings = [
    "Summoned using \"{CARD_NAME}\"",
    "Affected by effect \"{CARD_NAME}\": \"HERO\" monsters you control cannot be destroyed by battle",
    "Make 1 monster your opponent controls loses 800 ATK and DEF",
]

[elemental-hero-thunderman]
id = 900002112
alias = 20721928
name = "Elemental HERO Thunderman"
set = "elemental-hero"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 4
atk = 1600
def = 1400
effect = """\
(This card's name is always treated as "Elemental HERO Sparkman".)
This card is treated as a Normal Monster while face-up on the field or in the hand, GY. \
You can Tribute this card; Special Summon 1 of your banished "HERO" monsters. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● Once per turn, if this card battles a monster, during damage calculation: \
    You can make this card gains ATK equal to half the ATK of the opponent's monster it is battling \
    during that damage calculation only.
"""
strings = [
    "Summoned using \"{CARD_NAME}\"",
    "Tribute itself & Special Summon 1 banished \"HERO\" monsters",
    "Make this card gains ATK equal to half the ATK of the opponent's monster it is battling",
]

[elemental-hero-aquaman]
id = 900002113
alias = 79979666
name = "Elemental HERO Aquaman"
set = "elemental-hero"
type = "monster effect"
attribute = "water"
race = "warrior"
level = 4
atk = 800
def = 1200
effect = """\
(This card's name is always treated as "Elemental HERO Bubbleman".)
This card is treated as a Normal Monster while face-up on the field or in the hand, GY. \
If this card is Special Summoned by the effect of a "HERO" monster: You can draw 2 cards. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● Your opponent cannot target this card with monster effects.
"""
strings = ["Summoned using \"{CARD_NAME}\""]

[elemental-hero-shadownshade]
id = 900002114
alias = 89252153
name = "Elemental HERO Shadownshade"
set = "elemental-hero"
type = "monster effect"
attribute = "dark"
race = "warrior"
level = 5
atk = 1600
def = 1800
effect = """\
(This card's name is always treated as "Elemental HERO Necroshade".)
This card is treated as a Normal Monster while face-up on the field or in the hand, GY. \
When you Fusion Summon a "HERO" Fusion Monster, you can banish this card from your GY as materials. \
A "Elemental HERO" Fusion Monster that was Special Summoned using this card gains these effects.
● Once per turn (Quick Effect): You can target 1 other monster on the field; \
    until the End Phase, its effect are negated and banish it when it leaves the field.
"""
strings = [
    "Summoned using \"{CARD_NAME}\"",
    "Negate the effect of 1 monster & banish it when it leaves the field",
]

[neo-spacian-black-panther]
id = 900002115
name = "Neo-Spacian Black Panther"
set = "neo-spacian"
type = "monster fusion effect"
attribute = "dark"
race = "beast"
level = 4
atk = 1300
def = 800
effect = """\
This card's name is also treated as "Neo-Spacian Dark Panther". \
This card cannot be Special Summoned except with "NEX". \
Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; \
    until the End Phase, this card's name becomes that monster's original name, \
    also replace this effect with that monster's original effects (if any). \
"""
strings = ["Copy monster's name and effects"]

[neo-spacian-terra-mole]
id = 900002116
name = "Neo-Spacian Terra Mole"
set = "neo-spacian"
type = "monster fusion effect"
attribute = "earth"
race = "rock"
level = 4
atk = 1100
def = 500
effect = """\
This card's name is also treated as "Neo-Spacian Grand Mole". \
This card cannot be Special Summoned except with "NEX". \
At the start of the Damage Step, if this card battles an opponent's monster: \
    You can return the opponent's monster to the hand. \
"""
strings = ["Return the opponent's monster to the hand"]

[neo-spacian-sky-hummingbird]
id = 900002117
name = "Neo-Spacian Sky Hummingbird"
set = "neo-spacian"
type = "monster fusion effect"
attribute = "wind"
race = "winged-beast"
level = 4
atk = 1000
def = 800
effect = """\
This card's name is also treated as "Neo-Spacian Air Hummingbird". \
This card cannot be Special Summoned except with "NEX". \
Once per turn: You can gain 500 LP for each card in your hand. \
"""
strings = ["Gain 500 LP for each card in your hand"]

[neo-spacian-blaze-scarab]
id = 900002118
name = "Neo-Spacian Blaze Scarab"
set = "neo-spacian"
type = "monster fusion effect"
attribute = "fire"
race = "insect"
level = 4
atk = 800
def = 800
effect = """\
This card's name is also treated as "Neo-Spacian Flare Scarab". \
This card cannot be Special Summoned except with "NEX". \
Gains 400 ATK for each Spell/Trap you controls. \
"""
strings = []

[neo-spacian-pure-heart]
id = 900002119
name = "Neo-Spacian Pure Heart"
set = "neo-spacian"
type = "monster link effect"
attribute = "dark"
race = "fiend"
link = 1
link-arrow = "bottom"
atk = 0
effect = """\
1 level 4 or lower "HERO" or "Neo-Spacian" monster
If this card is Link Summoned: \
    You can Special Summon 1 LIGHT "Neos" monster or 1 Level 10 "Yubel" monster \
    from your hand or Deck, but it cannot attack this turn. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
Once per turn (Quick Effect): \
    You can send 1 "Neo-Spacian" monster, except "{CARD_NAME}", \
    from your hand, Deck or Extra Deck to the GY, and if you do, \
    until the End Phase, this card's name becomes that monster's original name, \
    and replace this effect with that monster's original effects. \
"""
strings = ["Copy name and effect of other \"Neo-Spacian\""]

[favorite-fusion]
id = 900002120
name = "Favorite Fusion"
set = "favorite fusion"
type = "spell"
effect = """\
Fusion Summon 1 "Elemental HERO" Fusion Monster from your Extra Deck, \
    using "HERO" monsters from your hand or Deck as Fusion Material, \
    also for the rest of this turn after this card resolves, \
    you cannot Special Summon monsters, except "HERO" monsters. \
You can only activate 1 "{CARD_NAME}" per turn. \
"""
strings = [
    "Affected by effect \"{CARD_NAME}\": cannot Special Summon monsters, except \"HERO\" monsters",
]

[contact-call]
id = 900002121
name = "Contact Call"
type = "spell"
effect = """\
Send 1 Normal Spell or Normal Trap that lists a "Neo-Spacian" card, \
    except "{CARD_NAME}", from your hand or Deck to the GY; \
    this effect becomes that Spell's effect when that card is activated. \
During your End Phase, if this card is in your GY: \
    You can target 1 Spell/Trap that mentions "Elemental HERO Neos" or lists a "Neo-Spacian" card, \
    that in your GY or banishment, except "{CARD_NAME}"; \
    shuffle both this card and that target into the Deck. \
You can only use 1 "{CARD_NAME}" effect per turn, and only once that turn. \
"""
strings = []

[clash-of-favorites]
id = 900002122
name = "Clash of Favorites"
set = "favorite"
type = "trap"
effect = """\
Special Summon from your hand or Deck to either player's field in Attack Position, \
    1 Level 10 "Yubel" monster, Level 10 "Ultimate Crystal" monster, or Level 10 "Armed Dragon" monster, \
    ignoring its Summoning conditions, but it cannot attack directly. \
    You can only Summon to your opponent's side of the field, unless you control "Elemental HERO Neos". \
During your Draw Phase, if this card is in your GY and you control "Elemental HERO Neos", before you draw: \
    You can shuffle this card into the Deck; \
    give up your normal draw this turn, and if you do, \
    add 1 "Super Polymerization" from your Deck or GY to your hand. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Special Summon to your field", "Special Summon to opponent's field"]

[favorite-soul]
id = 900002123
name = "Favorite Soul"
set = "favorite"
type = "trap continuous"
effect = """\
"Elemental HERO Neos" and all Fusion Monsters that lists it as material you control gain 500 ATK. \
If this face-up card leaves the field: Shuffle all monsters you control into the Deck. \
You can only use the following effect of "{CARD_NAME}" once per turn. You can activate 1 of these effects;
● Special Summon 1 "Elemental HERO Neos" from your hand or GY.
● Add 1 "Wrath of Neos" or "Contact Out" from your Deck to your hand. \
"""
strings = [
    "Special Summon 1 \"Elemental HERO Neos\"",
    "Add 1 \"Wrath of Neos\" or \"Contact Out\"",
]
